-- MATRICULAS_PAGO_DETALLE_TRANSFORMADO.csv
SELECT CODIGO_ESTUDIANTE FROM BlobStorage WHERE PERIODO = 202410;

-- CRITERIOS_RIESGO_HISTORICO_FINAL.csv
SELECT CODIGO_ESTUDIANTE, INDICE_MONITOREO_ADVISE, PORCENTAJE_CREDITOS_APROBADOS, PERIODO_EVALUADO FROM BlobStorage;